using System.Collections.Generic;
using TypeD.Code;

namespace TypeDCore.Code.Game
{
    class GameCode : Codalyzer
    {
        // Constructors
        public GameCode() : base()
        {
            AutoGeneratedFile = false;
            PartialClass = true;
            TypeDClass = false;

            BaseClass = "Game";
        }

        public override void Init()
        {
            Init($"{Project.ProjectName}Game", $"{Project.ProjectName}");

            Usings.AddRange(new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            });

            AddFunction(new Function("protected void InternalInitialize()", () => { }));
            AddFunction(new Function("protected void InternalCleanup()", () => { }));
        }
    }
}
