using System.Collections.Generic;
using TypeD;
using TypeD.Helpers;
using TypeD.Models;

namespace TypeDCore.Code
{
    class EntityTypeDCode : Codalyzer
    {
        public List<string> Drawables { get; set; } = new List<string>();

        public EntityTypeDCode(ProjectModel project, string className, string @namespace) : base(project, className, @namespace)
        {
            var drawablesStartBlock = "//Drawables start block";
            var drawablesEndBlock = "//Drawables end block";

            AutoGeneratedFile = true;
            PartialClass = true;
            TypeDClass = true;

            BaseClass = "Entity2d";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core.Entities"
            };

            AddFunction(new Function("public override void Initialize()", () => {
                if (Drawables.Count > 0)
                {
                    Writer.AddLine(drawablesStartBlock);
                    foreach (var drawable in Drawables)
                    {
                        Writer.AddLine($"Drawables.Create<{drawable}>();");
                    }
                    Writer.AddLine(drawablesEndBlock);
                }

                Writer.AddLine("InternalInitialize();");
            }));

            Drawables = FileHelper.FetchStringList(FilePath(), drawablesStartBlock, drawablesEndBlock);
        }
    }
}
