using System.Collections.Generic;
using TypeD;
using TypeD.Models;

namespace TypeDCore.Code.Entity
{
    class EntityCode : Codalyzer
    {
        public EntityCode(ProjectModel project, string className, string @namespace) : base(project, className, @namespace)
        {
            AutoGeneratedFile = false;
            PartialClass = true;
            TypeDClass = false;

            BaseClass = "Entity2d";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core.Entities"
            };

            AddFunction(new Function("protected void InternalInitialize()", () => { }));
            AddFunction(new Function("public override void Cleanup()", () => { }));
        }
    }
}
