using System;
using System.Collections.Generic;
using TypeD.Helpers;
using TypeD.Models.Data;
using TypeOEngine.Typedeaf.Core.Entities;
using TypeOEngine.Typedeaf.Core.Entities.Interfaces;
using TypeOEngine.Typedeaf.Core.Interfaces;

namespace TypeDCore.Code.Entity
{
    class EntityTypeDCode : ComponentTypeCode
    {
        // Properties
        public override Type TypeOBaseType { get { return typeof(Entity2d); } }
        public bool Updatable { get; private set; }
        public bool Drawable { get; private set; }
        public List<string> Drawables { get; set; }

        // Constructors
        public EntityTypeDCode(string className, string @namespace, Component parentComponentType, bool updatable, bool drawable) : base(className, @namespace, parentComponentType)
        {
            Updatable = updatable;
            Drawable = drawable;
            Drawables = new List<string>();
        }

        // Functions
        public override void Init()
        {
            AutoGeneratedFile = true;
            PartialClass = true;
            TypeDClass = true;

            var drawablesStartBlock = "//Drawables start block";
            var drawablesEndBlock = "//Drawables end block";

            AddFunction(new Function("public override void Initialize()", () => {
                if (!IsBaseComponentType)
                {
                    Writer.AddLine("base.Initialize();");
                }
                if (Drawables.Count > 0)
                {
                    Writer.AddLine(drawablesStartBlock);
                    foreach (var drawable in Drawables)
                    {
                        Writer.AddLine($"Drawables.Create<{drawable}>();");
                    }
                    Writer.AddLine(drawablesEndBlock);
                }

                if (IsBaseComponentType)
                {
                    Writer.AddLine("InternalInitialize();");
                }
            }));

            if (Updatable && (ParentComponent == null || !ParentComponent.Interfaces.Contains(typeof(IUpdatable))))
            {
                Usings.Add("TypeOEngine.Typedeaf.Core.Interfaces");
                AddInterface(typeof(IUpdatable));
                AddProperty(new Property("public bool Pause"));
            }

            if (Drawable && (ParentComponent == null || !ParentComponent.Interfaces.Contains(typeof(IDrawable))))
            {
                Usings.Add("TypeOEngine.Typedeaf.Core.Entities.Interfaces");
                AddInterface(typeof(IDrawable));
                AddProperty(new Property("public bool Hidden"));
                AddProperty(new Property("public int DrawOrder"));
            }

            Drawables = FileHelper.FetchStringList(FilePath(), drawablesStartBlock, drawablesEndBlock);
        }
    }
}
