using System.Collections.Generic;
using TypeD.Models;

namespace TypeD.Code
{
    class EntityTypeDCode : Codalyzer
    {
        public EntityTypeDCode(ProjectModel project, string className, string @namespace) : base(project, className, $"{project.ProjectName}.{@namespace}")
        {
            AutoGeneratedFile = true;
            PartialClass = true;
            TypeDClass = true;

            BaseClass = "Entity";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core.Entities"
            };
        }
    }
}
