using System.Collections.Generic;
using TypeD.Models;

namespace TypeD.Code
{
    class EntityCode : Codalyzer
    {
        public EntityCode(ProjectModel project, string className, string @namespace) : base(project, className, $"{project.ProjectName}.{@namespace}")
        {
            AutoGeneratedFile = false;
            PartialClass = true;
            TypeDClass = false;

            BaseClass = "Entity";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core.Entities"
            };

            AddFunction(new Function("public override void Initialize()", () => { }));
            AddFunction(new Function("public override void Cleanup()", () => { }));
        }
    }
}
