using System.Collections.Generic;
using TypeD.Models;

namespace TypeD.Code
{
    class GameTypeDCode : Codalyzer
    {
        public GameTypeDCode(ProjectModel project) : base(project, $"{project.ProjectName}Game", $"{project.ProjectName}")
        {
            AutoGeneratedFile = true;
            PartialClass = true;
            TypeDClass = true;

            BaseClass = "Game";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            };
        }
    }
}
