using System.Collections.Generic;
using System.IO;
using TypeD.Models;

namespace TypeD.Code
{
    public class GameCode : Codalyzer
    {
        public GameCode(ProjectModel project) : base(project, $"{project.ProjectName}Game", $"{project.ProjectName}")
        {
            AddAutoGeneratedComment = false;

            BaseClass = "Game";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            };

            AddFunction(new Function("public override void Initialize()", () => { }));
            AddFunction(new Function("public override void Draw()", () => { }));
            AddFunction(new Function("public override void Update(double dt)", () => { }));
            AddFunction(new Function("public override void Cleanup()", () => { }));
        }
    }
}
