using System.Collections.Generic;
using TypeD.Models;

namespace TypeD.Code
{
    class GameCode : Codalyzer
    {
        public GameCode(ProjectModel project) : base(project, $"{project.ProjectName}Game", $"{project.ProjectName}")
        {
            AutoGeneratedFile = false;
            PartialClass = true;
            TypeDClass = false;

            BaseClass = "Game";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            };

            AddFunction(new Function("protected void InternalInitialize()", () => { }));
            AddFunction(new Function("protected void InternalCleanup()", () => { }));
        }
    }
}
