using System.Collections.Generic;

namespace TypeD.Code
{
    class ProgramCode : Codalyzer
    {
        public ProgramCode() : base()
        {
            AutoGeneratedFile = true;
            PartialClass = false;
            TypeDClass = false;
        }

        public override void Init()
        {
            Init("Program", $"{Project.ProjectName}");

            Usings.AddRange(new List<string>()
            {
                "TypeOEngine.Typedeaf.Core.Engine"
            });

            DynamicUsings = () =>
            {
                var usings = new List<string>();

                foreach (var module in Project.Modules)
                {
                    var moduleType = module.ModuleTypeInfo;
                    if (moduleType == null || moduleType.Name == "TypeOCore" || module.IsTypeD) continue;
                    if (module.ModuleTypeInfo != null)
                        usings.Add(module.ModuleTypeInfo.Namespace);
                }

                return usings;
            };

            AddFunction(new Function($"static void Main()", () =>
            {
                Writer.AddLine($"TypeO.Create<{Project.ProjectName}Game>(\"{Project.ProjectName}\")");
                foreach (var module in Project.Modules)
                {
                    var moduleType = module.ModuleTypeInfo;
                    if (moduleType == null || moduleType.Name == "TypeOCore" || module.IsTypeD) continue;
                    Writer.AddLine($".LoadModule<{moduleType.Name}>()");
                }
                Writer.AddLine(".Start();", true);
                Writer.Tabs--;
            }));
        }
    }
}