using System.Collections.Generic;
using TypeD.Helpers;
using TypeD.Models;

namespace TypeD.Code
{
    class SceneTypeDCode : Codalyzer
    {
        public List<string> Entities { get; set; } = new List<string>();

        public SceneTypeDCode(ProjectModel project, string className, string @namespace) : base(project, className, @namespace)
        {
            var entityStartBlock = "//Entity start block";
            var entityEndBlock = "//Entity end block";

            AutoGeneratedFile = true;
            PartialClass = true;
            TypeDClass = true;

            BaseClass = "Scene";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            };

            AddFunction(new Function("public override void Initialize()", () => {
                if(Entities.Count > 0)
                {
                    Writer.AddLine(entityStartBlock);
                    foreach(var entity in Entities)
                    {
                        Writer.AddLine($"Entities.Create<{entity}>();");
                    }
                    Writer.AddLine(entityEndBlock);
                }

                Writer.AddLine("InternalInitialize();");
            }));

            AddFunction(new Function("public override void Update(double dt)", () => {
                Writer.AddLine("Entities.Update(dt);");
                Writer.AddLine("UpdateLoop.Update(dt);");
            }));
            AddFunction(new Function("public override void Draw()", () => {
                Writer.AddLine("DrawStack.Draw(null);");
            }));

            Entities = FileHelper.FetchStringList(FilePath(), entityStartBlock, entityEndBlock);
        }
    }
}
