using System.Collections.Generic;
using TypeD.Models;

namespace TypeD.Code
{
    class SceneCode : Codalyzer
    {
        public SceneCode(ProjectModel project, string className, string @namespace) : base(project, className, $"{project.ProjectName}.{@namespace}")
        {
            AutoGeneratedFile = false;
            PartialClass = true;
            TypeDClass = false;

            BaseClass = "Scene";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            };

            AddFunction(new Function("public override void Initialize()", () => { }));
            AddFunction(new Function("public override void Update(double dt)", () => { }));
            AddFunction(new Function("public override void Draw()", () => { }));
            AddFunction(new Function("public override void OnEnter(Scene from)", () => { }));
            AddFunction(new Function("public override void OnExit(Scene to)", () => { }));
        }
    }
}
