using System.Collections.Generic;
using TypeD;

namespace TypeDCore.Code.Drawable2d
{
    class Drawable2dCode : Codalyzer
    {
        public Drawable2dCode(string className, string @namespace) : base()
        {
            Init(className, @namespace);
            AutoGeneratedFile = false;
            PartialClass = false;
            TypeDClass = false;

            BaseClass = "Drawable2d";
        }

        public override void Init()
        {
            Usings.AddRange(new List<string>()
            {
                "TypeOEngine.Typedeaf.Core.Common",
                "TypeOEngine.Typedeaf.Core.Engine.Graphics",
                "TypeOEngine.Typedeaf.Core.Entities.Drawables"
            });

            AddProperty(new Property("public override Vec2 Size", () => { Writer.AddLine("get; protected set;"); }));
            AddFunction(new Function("public override void Initialize()", () => { }));
            AddFunction(new Function("public override void Draw(Canvas canvas)", () => { }));
            AddFunction(new Function("public override void Cleanup()", () => { }));
        }
    }
}