using System.Collections.Generic;
using TypeD;
using TypeD.Models.Data;

namespace TypeDCore.Code.Drawable2d
{
    class Drawable2dCode : Codalyzer
    {
        public Drawable2dCode(Project project, string className, string @namespace) : base(project, className, @namespace)
        {
            AutoGeneratedFile = false;
            PartialClass = false;
            TypeDClass = false;

            BaseClass = "Drawable2d";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core.Common",
                "TypeOEngine.Typedeaf.Core.Engine.Graphics",
                "TypeOEngine.Typedeaf.Core.Entities.Drawables"
            };

            AddProperty(new Property("public override Vec2 Size", () => { Writer.AddLine("get; protected set;"); }));
            AddFunction(new Function("public override void Initialize()", () => { }));
            AddFunction(new Function("public override void Draw(Canvas canvas)", () => { }));
            AddFunction(new Function("public override void Cleanup()", () => { }));
        }
    }
}