using System.Collections.Generic;
using TypeD;
using TypeD.Helpers;

namespace TypeDCore.Code.Scene
{
    class SceneTypeDCode : Codalyzer
    {
        public List<string> Entities { get; set; } = new List<string>();

        public SceneTypeDCode(string className, string @namespace) : base()
        {
            Init(className, @namespace);
            AutoGeneratedFile = true;
            PartialClass = true;
            TypeDClass = true;

            BaseClass = "Scene";
        }

        public override void Init()
        {
            var entityStartBlock = "//Entity start block";
            var entityEndBlock = "//Entity end block";

            Usings.AddRange(new List<string>()
            {
                "TypeOEngine.Typedeaf.Core",
                "TypeOEngine.Typedeaf.Core.Common"
            });

            AddFunction(new Function("public override void Initialize()", () => {
                if (Entities.Count > 0)
                {
                    Writer.AddLine(entityStartBlock);
                    foreach (var entity in Entities)
                    {
                        Writer.AddLine($"Entities.Create<{entity}>();");
                    }
                    Writer.AddLine(entityEndBlock);
                }

                Writer.AddLine("InternalInitialize();");
            }));

            AddFunction(new Function("public override void Update(double dt)", () => {
                Writer.AddLine("Entities.Update(dt);");
                Writer.AddLine("UpdateLoop.Update(dt);");
            }));
            AddFunction(new Function("public override void Draw()", () => {
                Writer.AddLine("Canvas.Clear(Color.Black);");
                Writer.AddLine("DrawStack.Draw(Canvas);");
                Writer.AddLine("Canvas.Present();");
            }));

            Entities = FileHelper.FetchStringList(FilePath(), entityStartBlock, entityEndBlock);
        }
    }
}
