using System;
using System.Collections.Generic;

namespace TypeDCore.Code.Scene
{
    class SceneCode : ComponentTypeCode
    {
        // Properties
        public override Type BaseComponentType { get { return typeof(TypeOEngine.Typedeaf.Core.Scene); } }

        // Constructors
        public SceneCode(string className, string @namespace, string baseClass) : base(className, @namespace, baseClass)
        {
        }

        // Functions
        public override void Init()
        {
            AutoGeneratedFile = false;
            PartialClass = true;
            TypeDClass = false;

            Usings.AddRange(new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            });

            if(IsBaseComponentType)
            {
                AddFunction(new Function("protected virtual void InternalInitialize()", () => { }));
                AddFunction(new Function("public override void OnEnter(Scene from)", () => { }));
                AddFunction(new Function("public override void OnExit(Scene to)", () => { }));
            }
            else
            {
                AddFunction(new Function("protected override void InternalInitialize()", () => {
                    Writer.AddLine("base.InternalInitialize();");
                }));
                AddFunction(new Function("public override void OnEnter(Scene from)", () => {
                    Writer.AddLine("base.OnEnter(from);");
                }));
                AddFunction(new Function("public override void OnExit(Scene to)", () => {
                    Writer.AddLine("base.OnExit(to);");
                }));
            }
        }
    }
}
