using System.Collections.Generic;
using TypeD;
using TypeD.Models;

namespace TypeDCore.Code.Scene
{
    class SceneCode : Codalyzer
    {
        public SceneCode(ProjectModel project, string className, string @namespace) : base(project, className, @namespace)
        {
            AutoGeneratedFile = false;
            PartialClass = true;
            TypeDClass = false;

            BaseClass = "Scene";
            Usings = new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            };

            AddFunction(new Function("protected void InternalInitialize()", () => { }));
            AddFunction(new Function("public override void OnEnter(Scene from)", () => { }));
            AddFunction(new Function("public override void OnExit(Scene to)", () => { }));
        }
    }
}
