using System.Collections.Generic;
using TypeD;

namespace TypeDCore.Code.Scene
{
    class SceneCode : Codalyzer
    {
        public SceneCode(string className, string @namespace) : base()
        {
            Init(className, @namespace);
            AutoGeneratedFile = false;
            PartialClass = true;
            TypeDClass = false;

            BaseClass = "Scene";
        }

        public override void Init()
        {
            Usings.AddRange(new List<string>()
            {
                "TypeOEngine.Typedeaf.Core"
            });

            AddFunction(new Function("protected void InternalInitialize()", () => { }));
            AddFunction(new Function("public override void OnEnter(Scene from)", () => { }));
            AddFunction(new Function("public override void OnExit(Scene to)", () => { }));
        }
    }
}
